name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '⚠️ BREAKING CHANGES ⚠️'
    labels:
      - 'pr-breaking'
  - title: 'Features/Enhancements'
    labels:
      - 'pr-feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'pr-bugfix'
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'docs'

include-labels:
  - pr-breaking
  - pr-feature
  - enhancement
  - fix
  - pr-bugfix
  - bug
  - docs
exclude-labels:
  - pr-nochangelog
exclude-contributors:
  - github-actions
  - github-actions[bot]

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'pr-breaking'
  minor:
    labels:
      - 'pr-feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'pr-bugfix'
      - 'bug'
  default: patch

template: |
  ---
  **⚠️ Compatibility Warning ⚠️**

  Releases of this collection are compatible with their corresponding `step-cli/ca` minor version.
  In particular, this release (`$RESOLVED_VERSION`) is compatible with `step-cli/ca` `$NEXT_MINOR_VERSION`.
  Other versions may work, but are not supported.

  Please make sure to use the appropriate collection version for your version of the step tools.

  Breaking changes may happen between minor development releases (e.g. 0.20 -> 0.21).

  ---

  ## Changes

  $CHANGES
