---
- name: Verify
  hosts: panel
  gather_facts: false
  tasks:
    - name: Get panel homepage # noqa risky-file-permissions
      get_url:
        url: https://127.0.0.1
        dest: /tmp/index.html
        validate_certs: no
    - name: Get homepage contents
      command: cat /tmp/index.html
      changed_when: no
      register: pterodactyl_panel_page
    - name: Verify that homepage was loaded
      assert:
        that:
          - '"Pterodactyl" in pterodactyl_panel_page.stdout'
