authors:
- Max Hösel <ansible@maxhoesel.de>
build_ignore:
- '*.tar.gz'
- .venv
- .github
- .tox
- .pytest_cache
- scripts
dependencies: {}
description: Manage Pterodactyl panel and wings hosts
documentation: https://github.com/maxhoesel/ansible-collection-pterodactyl
homepage: https://github.com/maxhoesel/ansible-collection-pterodactyl
issues: https://github.com/maxhoesel/ansible-collection-pterodactyl/issues
license_file: LICENSE
name: pterodactyl
namespace: maxhoesel
readme: README.md
repository: https://github.com/maxhoesel/ansible-collection-pterodactyl
tags:
- pterodactyl
- games
version: 0.4.2
