authors:
- Max Hösel <ansible@maxhoesel.de>
build_ignore:
- .circleci
- .github
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- pyproject.toml
- tox.ini
- .yamllint
- .ansible-lint
- .pre-commit-config.yaml
- '*.tar.gz'
- .venv
- .tox
- .pytest_cache
- scripts
- requirements.txt
- requirements-molecule.txt
- '**/requirements-molecule.txt'
- '**/requirements.txt'
dependencies: {}
description: Manage Pterodactyl panel and wings hosts
documentation: https://github.com/maxhoesel/ansible-collection-pterodactyl
homepage: https://github.com/maxhoesel/ansible-collection-pterodactyl
issues: https://github.com/maxhoesel/ansible-collection-pterodactyl/issues
license_file: LICENSE
name: pterodactyl
namespace: maxhoesel
readme: README.md
repository: https://github.com/maxhoesel/ansible-collection-pterodactyl
tags:
- pterodactyl
- games
version: 0.5.1
