#!/usr/bin/env bash

set -eu
set -o pipefail

SCRIPT_DIRECTORY=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# shellcheck disable=1091
source "$SCRIPT_DIRECTORY/constants.sh"

tox -e sanity -- \
    --docker --color -v \
    --python "$PYTHON_VERSION"
