---
# handlers file for pterodactyl_wings
- name: restart wings
  systemd:
    name: wings.service
    state: restarted

- name: reload docker
  systemd:
    name: docker.service
    state: reloaded

- name: restart host
  reboot:
