---
- name: Converge
  hosts: panel
  tasks:
    - name: "Include pterodactyl_panel"
      include_role:
        name: "pterodactyl_panel"
      vars:
        pterodactyl_panel_webroot: /var/www/pterodactyl-molecule
        pterodactyl_panel_ssl_cert: /etc/ssl/private/pterodactyl.crt
        pterodactyl_panel_ssl_key: /etc/ssl/private/pterodactyl.key
        pterodactyl_panel_app_key: base64:plc67JdoBykgQPhTJV8BCu1MDAYM0QRbZt93mnh/uyE=
        pterodactyl_panel_hashids_salt: YhQ1W5XhR1cTZGMLK16a
        pterodactyl_panel_db_host: pterodactyl-panel-db.localdomain
        pterodactyl_panel_db_name: panel_molecule
        pterodactyl_panel_db_user: panel_molecule
        pterodactyl_panel_db_password: panel_molecule
