---
- name: Converge
  hosts: panel
  tasks:
    - name: "Include pterodactyl_panel"
      include_role:
        name: "pterodactyl_panel"
      vars:
        pterodactyl_panel_webroot: /var/www/pterodactyl-molecule
        pterodactyl_panel_ssl_cert: /etc/ssl/private/pterodactyl.crt
        pterodactyl_panel_ssl_key: /etc/ssl/private/pterodactyl.key
        pterodactyl_panel_app_key: base64:plc67JdoBykgQPhTJV8BCu1MDAYM0QRbZt93mnh/uyE=
        pterodactyl_panel_hashids_salt: YhQ1W5XhR1cTZGMLK16a
        pterodactyl_panel_version: "{{ panel_version }}"
        pterodactyl_panel_db_host: "{{ db_host }}"
        pterodactyl_panel_db_name: "{{ db_name }}"
        pterodactyl_panel_db_user: "{{ db_username }}"
        pterodactyl_panel_db_password: "{{ db_password }}"
