---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/default/collections/requirements.yml
    role-file: molecule/default/collections/requirements.yml
driver:
  name: docker
  network:
    - name: pterodactyl_panel
      driver: bridge
platforms:
  - name: pterodactyl-panel-db
    hostname: pterodactyl-panel-db.localdomain
    image: mariadb
    pre_build_image: true
    override_command: false
    env:
      MYSQL_ROOT_PASSWORD: panel_molecule
      MYSQL_DATABASE: panel_molecule
      MYSQL_USER: panel_molecule
      MYSQL_PASSWORD: panel_molecule
    networks:
      - name: pterodactyl_panel

  - name: pterodactyl-panel-ubuntu-20
    hostname: pterodactyl-panel-ubuntu-20.localdomain
    image: "geerlingguy/docker-ubuntu2004-ansible"
    groups:
      - panel
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    override_command: false
    pre_build_image: true
    networks:
      - name: pterodactyl_panel
    # Uncomment to access the panel from your machine.
    # Useful for debugging purposes
    #published_ports:
    #  - 0.0.0.0:8443:443/tcp

provisioner:
  name: ansible
  config_options:
    ssh_connection:
      pipelining: yes

scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check # also run check mode in regular tests
    - side_effect
    - verify
    - destroy
      
verifier:
  name: ansible
