- hosts: panel
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install MySQL
      include_role:
        name: geerlingguy.mysql
      vars:
        mysql_root_password: super-secure-password
        mysql_databases:
          - name: panel_molecule
            encoding: utf8mb4
            collation: utf8mb4_general_ci
        mysql_users:
          - name: panel_molecule
            host: "%"
            password: panel_molecule
            priv: "panel_molecule.*:ALL"

    - name: Copy existing SSL cert/key to nodes
      copy:
        src: "{{ item }}"
        dest: /etc/ssl/private/
        owner: root
        group: root
        mode: 0755 # this is insecure, don't do this in prod
      loop:
        - "pterodactyl.crt"
        - "pterodactyl.key"
