- hosts: panel
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: SSL cert directory exists
      ansible.builtin.file:
        path: /etc/letsencrypt/live/{{ ansible_fqdn }}/
        state: directory
        owner: root
        group: root
        mode: "755"
    - name: Copy existing SSL cert/key to fake letsencrypt directory
      copy:
        src: "{{ item }}"
        dest: /etc/letsencrypt/live/{{ ansible_fqdn }}/
        owner: root
        group: root
        mode: 0755 # this is insecure, don't do this in prod
      loop:
        - "fullchain.pem"
        - "privkey.pem"
