---
- name: Verify
  hosts: panel
  tasks:
    - name: Get panel homepage
      ansible.builtin.uri:
        url: "https://{{ pterodactyl_panel_domain }}"
        ca_path: "{{ pterodactyl_panel_ssl_cert }}"
        return_content: true
      register: page
    - name: Verify that homepage was loaded
      assert:
        that:
          - '"Pterodactyl" in page.content'

    - name: Get Pterodactyl env file # noqa no-changed-when
      ansible.builtin.command: cat {{ pterodactyl_panel_webroot }}/.env
      register: _pterodactyl_panel_enffile
    - name: Print pterodactyl env file
      debug:
        var: _pterodactyl_panel_enffile
