- name: Look for existing config file
  stat:
    path: "{{ pterodactyl_wings_config_dir }}/config.yml"
  register: _pterodactyl_wings_config_file

- name: Generate Wings Config
  block:
    - name: Read current configuration
      command: "cat {{ pterodactyl_wings_config_dir }}/config.yml"
      register: _pterodactyl_wings_config_current
      changed_when: no
      check_mode: no
    - name: Merge existing configuration new config
      set_fact:
        pterodactyl_wings_config: "{{ _pterodactyl_wings_config_current.stdout | from_yaml | combine(pterodactyl_wings_config, recursive=True) }}"
  when: _pterodactyl_wings_config_file.stat.exists

- name: Wings config file is installed
  template:
    src: config.yml.j2
    dest: "{{ pterodactyl_wings_config_dir }}/config.yml"
    owner: root
    group: root
    mode: 0640
  notify: restart wings
  when: (_pterodactyl_wings_config_current.stdout|from_yaml)|default({}) != pterodactyl_wings_config
