- name: Uninstall packages provided by docker.com repository
  apt:
    name: "{{ _pterodactyl_wings_docker_stable_packages }}"
    state: absent

- name: Ensure docker.com repository is absent
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: yes
    state: absent

- name: Docker is installed from distro packages
  apt:
    update_cache: yes
    name: docker.io
