- name: Get package facts
  ansible.builtin.package_facts:

- name: Docker is installed from distro packages
  apt:
    update_cache: yes
    name: docker.io
  when: "'docker-ce' not in ansible_facts.packages" # ensure we don't override an existing upstream docker install

- name: Enable IPv6 suppport
  include_tasks: docker_ipv6.yml
  when: pterodactyl_wings_docker_ipv6

- name: Docker is enabled and running
  systemd:
    name: docker
    state: started
    enabled: yes
