- name: APT repository dependencies are installed
  apt:
    update_cache: yes
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Distribution-provided docker packages are absent
  apt:
    name: "{{ _pterodactyl_wings_docker_distro_packages }}"
    state: absent

- name: Add docker.com key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker.com repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: yes

- name: Install docker from the docker.com repository
  apt:
    name: "{{ _pterodactyl_wings_docker_stable_packages }}"
