- name: Install docker from {{ pterodactyl_wings_docker_source }}
  include_tasks: "docker_{{ pterodactyl_wings_docker_source }}.yml"

- name: Docker is enabled and running
  systemd:
    name: docker
    state: started
    enabled: yes
