- name: APT repository dependencies are installed
  apt:
    update_cache: yes
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Distribution-provided docker packages are absent
  apt:
    name: "{{ _pterodactyl_wings_docker_distro_packages }}"
    state: absent

- name: Old docker.com key in central keyring is absent
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: absent
- name: /etc/apt/keyrings exists
  file:
    state: directory
    name: /etc/apt/keyrings
    mode: "755"
    owner: root
    group: root
- name: docker.com key is in repo-specific keyring
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    keyring: /etc/apt/keyrings/docker.gpg

- name: Add docker.com repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    update_cache: yes

- name: Install docker from the docker.com repository
  apt:
    name: "{{ _pterodactyl_wings_docker_stable_packages }}"
