---
# tasks file for pterodactyl_wings
- name: Install docker
  include_tasks: "docker.yml"
  when: pterodactyl_wings_docker_install

- name: Wings config dir exists
  file:
    path: "{{ pterodactyl_wings_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Set specific version download URL
  set_fact:
    pterodactyl_wings_url: "https://github.com/pterodactyl/wings/releases/download/{{ pterodactyl_wings_version }}/wings_linux_amd64"
  when: pterodactyl_wings_version != "latest"
- name: Set latest download URL
  set_fact:
    pterodactyl_wings_url: "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_amd64"
  when: pterodactyl_wings_version == "latest"

- name: Wings is installed
  get_url:
    url: "{{ pterodactyl_wings_url }}"
    dest: /usr/local/bin/wings
    owner: root
    group: root
    mode: "755"
  notify: restart wings

- name: Configure Wings
  ansible.builtin.include_tasks: config.yml
  when: pterodactyl_wings_config_install

- name: Wings service file is present
  template:
    src: wings.service.j2
    dest: /etc/systemd/system/wings.service
    owner: root
    group: root
    mode: 0644
  notify: restart wings

- name: Wings is enabled
  ansible.builtin.systemd:
    daemon_reload: yes
    name: wings.service
    enabled: yes
  tags:
    - molecule-idempotence-notest

- name: Wings is started
  systemd:
    name: wings.service
    state: started
  tags:
    - molecule-idempotence-notest
  when: pterodactyl_wings_start
