---
# tasks file for pterodactyl_wings
- name: Install docker
  include_tasks: "docker.yml"
  when: pterodactyl_wings_docker_install

- name: Wings config dir exists
  file:
    path: "{{ pterodactyl_wings_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Set specific version download URL
  set_fact:
    pterodactyl_wings_url: "https://github.com/pterodactyl/wings/releases/download/{{ pterodactyl_wings_version }}/wings_linux_amd64"
  when: pterodactyl_wings_version != "latest"
- name: Set latest download URL
  set_fact:
    pterodactyl_wings_url: "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_amd64"
  when: pterodactyl_wings_version == "latest"

- name: Wings is installed
  get_url:
    url: "{{ pterodactyl_wings_url }}"
    dest: /usr/local/bin/wings
    owner: root
    group: root
    mode: "755"
  notify: restart wings

- name: Look for existing config file
  stat:
    path: "{{ pterodactyl_wings_config_dir }}/config.yml"
  register: _pterodactyl_wings_config_file

- name: Generate Wings Config
  block:
    - name: Read current configuration
      command: "cat {{ pterodactyl_wings_config_dir }}/config.yml"
      register: _pterodactyl_wings_config_current
      changed_when: no
      check_mode: no
    - name: Merge existing configuration new config
      set_fact:
        pterodactyl_wings_config: "{{ _pterodactyl_wings_config_current.stdout | from_yaml | combine(pterodactyl_wings_config, recursive=True) }}"
  when: _pterodactyl_wings_config_file.stat.exists

- name: Wings config file is installed
  template:
    src: config.yml.j2
    dest: "{{ pterodactyl_wings_config_dir }}/config.yml"
    owner: root
    group: root
    mode: 0640
  notify: restart wings
  when: (_pterodactyl_wings_config_current.stdout|from_yaml)|default({}) != pterodactyl_wings_config

- name: Wings service file is present
  template:
    src: wings.service.j2
    dest: /etc/systemd/system/wings.service
    owner: root
    group: root
    mode: 0644
  notify: restart wings

- name: Wings is enabled and running
  systemd:
    daemon_reload: yes
    name: wings.service
    enabled: yes
    state: started
  tags:
    - molecule-idempotence-notest
