---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.molecule.yml

driver:
  name: docker

provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: false

scenario:
  test_sequence:
    - dependency
    - syntax
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - check # also run check mode in regular tests
    - side_effect
    - verify
    - destroy

verifier:
  name: ansible
