---
dependency:
  name: galaxy

driver:
  name: docker

provisioner:
  name: ansible

scenario:
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check  # also run check mode in regular tests
    - side_effect
    - verify
    - destroy

verifier:
  name: ansible
