- name: Verify that required parameters are set
  assert:
    that:
      - pterodactyl_panel_app_key is defined
      - pterodactyl_panel_app_key | length > 0
      - pterodactyl_panel_hashids_salt is defined
      - pterodactyl_panel_hashids_salt | length > 0
      - pterodactyl_panel_db_password is defined
      - pterodactyl_panel_db_password | length > 0
    fail_msg: "The following parameters are required: pterodactyl_panel_app_key, pterodactyl_panel_hashids_salt, pterodactyl_panel_db_password"
