- name: Download and unpack pterodactyl
  unarchive:
    src: "{{ pterodactyl_panel_download_url }}"
    dest: "{{ pterodactyl_panel_webroot }}"
    owner: www-data
    group: www-data
    remote_src: yes

- name: Update owner/group for panel webroot
  file:
    path: "{{ pterodactyl_panel_webroot }}"
    owner: www-data
    group: www-data
    recurse: yes

- name: Ensure storage and bootstrap/cache have the correct permissions
  file:
    path: "{{ item }}"
    owner: www-data
    group: www-data
    mode: "755"
    recurse: yes
  loop:
    - "{{ pterodactyl_panel_webroot }}/storage"
    - "{{ pterodactyl_panel_webroot }}/bootstrap/cache"

- block:
  - name: Run composer install # noqa no-changed-when
    command: "composer install --no-dev --optimize-autoloader"
    args:
      chdir: "{{ pterodactyl_panel_webroot }}"
  - name: Run artisan migrate # noqa no-changed-when
    command: "php artisan migrate --seed --force"
    args:
      chdir: "{{ pterodactyl_panel_webroot }}"
  - name: Create initial user # noqa no-changed-when
    command: >
      php artisan p:user:make
      --email={{ pterodactyl_panel_admin_mail }}
      --username={{ pterodactyl_panel_admin_user }}
      --password={{ pterodactyl_panel_admin_password }}
      --name-first={{ pterodactyl_panel_admin_firstname }}
      --name-last={{ pterodactyl_panel_admin_lastname }}
      --admin=1
    no_log: yes
    args:
      chdir: "{{ pterodactyl_panel_webroot }}"
  become: yes
  become_user: www-data
