- name: Dependency packages are installed
  package:
    name:
      - "{% if pterodactyl_panel_webserver == 'apache2' %}apache2{% elif pterodactyl_panel_webserver == 'nginx' %}nginx{% endif %}"
      - "{% if pterodactyl_panel_webserver == 'apache2' %}libapache2-mod-php{% elif pterodactyl_panel_webserver == 'nginx' %}php-fpm{% endif %}"
      - php
      - php-pdo
      - php-gd
      - php-mysql
      - php-pdo
      - php-mbstring
      - php-tokenizer
      - php-bcmath
      - php-xml
      - php-curl
      - php-zip
      - composer
      - curl
      - unzip
      - git
      # Needed to ensure that become_user to www-data works
      - acl
