- name: Look for crontab executable
  #"command" is a shell builtin, hence the need for the shell module
  shell: "command -v crontab"
  register: _crontab_install
  # dash (Debian sh shell) uses 127 instead of 1 for not found errors
  failed_when: _crontab_install.rc not in [0,1,127]
  changed_when: no
  check_mode: no

# Schedules used to be run with cron, but we have since switched to systemd timers - make sure the old residue is gone.
- name: Old Schedule cronjob is absent
  cron:
    name: "Pterodactyl Panel - Schedule"
    state: absent
  register: _crontab_removal
  when: _crontab_install.rc == 0

- name: Schedule systemd service is present
  template:
    src: pterosched.service.j2
    dest: /etc/systemd/system/pterosched.service
    mode: "644"
    owner: root
    group: root
  notify: Restart schedule service
- name: Schedule systemd timer is present
  copy:
    src: pterosched.timer
    dest: /etc/systemd/system/pterosched.timer
    owner: root
    group: root
    mode: "644"
  notify: Restart schedule service
- name: Schedule timer is enabled and running
  systemd:
    daemon_reload: yes
    name: pterosched.timer
    enabled: yes
    state: started

- name: Queue listener service is installed
  template:
    src: pteroq.service.j2
    dest: /etc/systemd/system/pteroq.service
    mode: "644"
    owner: root
    group: root
  notify: Restart queue service
- name: Queue listener service is enabled
  systemd:
    daemon_reload: yes
    name: pteroq.service
    enabled: yes
