- name: Dependency packages are installed
  package:
    name:
      - apache2
      - libapache2-mod-php
      - php-pdo
      - php-gd
      - php-mysql
      - php-pdo
      - php-mbstring
      - php-tokenizer
      - php-bcmath
      - php-xml
      - php-curl
      - php-zip
      - composer
      - curl
      - unzip
      - git
      - redis-server
      # Needed to ensure that become_user to www-data works
      - acl
