- name: Enter maintenance mode # noqa no-changed-when
  command: php artisan down
  args:
    chdir: "{{ pterodactyl_panel_webroot }}"
  become: yes
  become_user: www-data

- name: Download and unpack pterodactyl
  unarchive:
    src: "{{ pterodactyl_panel_download_url }}"
    dest: "{{ pterodactyl_panel_webroot }}"
    owner: www-data
    group: www-data
    remote_src: yes

- name: Update owner/group for panel webroot
  file:
    path: "{{ pterodactyl_panel_webroot }}"
    owner: www-data
    group: www-data
    recurse: yes

- name: Ensure storage and bootstrap/cache have the correct permissions
  file:
    path: "{{ item }}"
    owner: www-data
    group: www-data
    mode: "755"
    recurse: yes
  loop:
    - "{{ pterodactyl_panel_webroot }}/storage"
    - "{{ pterodactyl_panel_webroot }}/bootstrap/cache"

- name: Run composer and artisan commands
  block:
  - name: Run composer install # noqa no-changed-when
    command: "composer install --no-dev --optimize-autoloader"
    args:
      chdir: "{{ pterodactyl_panel_webroot }}"

  - name: Clear compiled template cache # noqa no-changed-when
    command: "php artisan {{ item }}:clear"
    args:
      chdir: "{{ pterodactyl_panel_webroot }}"
    loop:
      - view
      - config

  - name: Update database # noqa no-changed-when
    command: php artisan migrate --seed --force
    args:
      chdir: "{{ pterodactyl_panel_webroot }}"

  - name: Restart queue workers # noqa no-changed-when
    command: php artisan queue:restart
    args:
      chdir: "{{ pterodactyl_panel_webroot }}"

  - name: Exit maintenance mode # noqa no-changed-when
    command: php artisan up
    args:
      chdir: "{{ pterodactyl_panel_webroot }}"
  become: yes
  become_user: www-data
