---
name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag? Format: x.y.z"
        required: true

jobs:
  create-release:
    name: "Create Release"
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          wget https://github.com/git-chglog/git-chglog/releases/download/v0.11.2/git-chglog_0.11.2_linux_amd64.tar.gz -O git-chglog.tar.gz
          tar xf git-chglog.tar.gz

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"

      - name: Set Galaxy version tag
        run: |
          sed -i '/version: */c\version: ${{ github.event.inputs.version }}' galaxy.yml

      - name: Generate full changelog
        run: "./git-chglog --next-tag v${{ github.event.inputs.version }} --output CHANGELOG.md"

      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          git commit -m "Release ${{ github.event.inputs.version }}"
          git push

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Release ${{ github.event.inputs.version }}"
          pr_body: "(This release PR was automatically generated via GitHub Actions)"
          github_token: ${{ secrets.GITHUB_TOKEN }}
